### ISSUE TITLE
Create the Main Side Navigation

### ISSUE THREAD

**Issue by codyseibert** [codyseibert/devtubers#1]
- A user shall be able to navigate between pages using a left side navigation
- clicking on the view source github link will loadup this repo in a new link
- clicking submit channel will route to a `/submit` page
- clicking about will route to an `/about` page
- clicking the /c/webdevjunkie will open a new link to my youtube channel
- clicking channels will redirect to `/channels` page
- clicking videos will redirect to `/videos` page
- clicking the logo at the top redirects to `/channels`

![Screen Shot 2021-03-12 at 8 53 22 PM](https://user-images.githubusercontent.com/1868782/111015059-fd0f1080-8374-11eb-8da9-63885bff2787.png)

**Comment by boybenson** [comment]
Wow Sir, I think this will be pretty cool for me to work on as someone who has never collborated on a project with another developer.....
can i please get access to the logo image?

**Comment by boybenson** [comment]
Wow Sir, I think this will be pretty cool for me to work on as someone who has never collborated on a project with another developer.....
can i please get access to the logo image?

**Comment by codyseibert** [comment]
@boybenson  

I'd like to use font awesome for the icons.  I think they have one similar to what you'd want there:

https://fontawesome.com/icons/laptop-code?style=solid

Here is the documentation for how to set it setup:

https://fontawesome.com/how-to-use/on-the-web/using-with/react
